[tool.pdm]

[project]
name = "AdventOfCodePy"
version = "1"
description = ""
authors = [{ name = "karanveersp", email = "karanv41@proton.me" }]
dependencies = []
requires-python = ">=3.11"
license = { text = "MIT" }
